[CmdletBinding()]
param(
  [Parameter(Mandatory)] [string] $RepositoryName,
  [Parameter(Mandatory)] [string] $Requester,
  [Parameter(Mandatory)] [ValidatePattern('^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$')] [string] $EnvironmentId
)

$ErrorActionPreference = 'Stop'
$env:REPOSITORY_GENERATION_POST_ATTEMPTED = 'false'
foreach ($name in @('GITHUB_TOKEN', 'GENERATED_REPOSITORY_OWNER', 'TEMPLATE_REPOSITORY_OWNER', 'TEMPLATE_REPOSITORY_NAME')) {
  if (-not [Environment]::GetEnvironmentVariable($name)) { throw "$name is required." }
}
if ($RepositoryName -notmatch '^[a-z0-9](?:[a-z0-9-]{1,48}[a-z0-9])$') { throw 'Unsafe repository name.' }

$headers = @{
  Authorization = "Bearer $($env:GITHUB_TOKEN)"
  Accept = 'application/vnd.github+json'
  'X-GitHub-Api-Version' = '2026-03-10'
}
$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$canonicalRoot = Join-Path $root 'scaffolds/application/base'
. (Join-Path $PSScriptRoot 'GitHubRepositoryProvenance.ps1')
$canonicalTree = Get-CanonicalTree -CanonicalRoot $canonicalRoot
$templateOwner = $env:TEMPLATE_REPOSITORY_OWNER
$templateName = $env:TEMPLATE_REPOSITORY_NAME
Assert-ExactCanonicalTree -Headers $headers -RepositoryOwner $templateOwner -RepositoryName $templateName -Expected $canonicalTree -RequireTemplate
$owner = $env:GENERATED_REPOSITORY_OWNER
$mode = if ($env:GENERATED_OWNER_MODE) { $env:GENERATED_OWNER_MODE } else { 'organization' }
if ($mode -eq 'personal' -and $Requester.ToLowerInvariant() -ne $owner.ToLowerInvariant()) {
  throw 'Personal mode permits requests only from the configured account owner.'
}
if ($mode -eq 'organization') {
  if (-not $env:PLATFORM_REPOSITORY) { throw 'PLATFORM_REPOSITORY is required in organization mode.' }
  if (-not $env:ORGANIZATION_REQUESTERS) {
    throw 'ORGANIZATION_REQUESTERS must contain the reviewed organization-member allowlist; failing closed.'
  }
  $allowedRequesters = @($env:ORGANIZATION_REQUESTERS.Split(',') | ForEach-Object { $_.Trim().ToLowerInvariant() } | Where-Object { $_ })
  if ($Requester.ToLowerInvariant() -notin $allowedRequesters) {
    throw "Requester $Requester is not in the reviewed organization-member allowlist."
  }
  try {
    Invoke-WebRequest -Method Get -Uri "https://api.github.com/orgs/$owner/members/$Requester" -Headers $headers -SkipHttpErrorCheck -StatusCodeVariable membershipStatus | Out-Null
    if ($membershipStatus -ne 204) { throw "GitHub did not confirm current organization membership for $Requester." }
  }
  catch { throw "Could not prove current organization membership for $Requester; failing closed. $($_.Exception.Message)" }
  $platformParts = $env:PLATFORM_REPOSITORY.Split('/', 2)
  if ($platformParts.Count -ne 2 -or $platformParts[0].ToLowerInvariant() -ne $owner.ToLowerInvariant()) {
    throw 'Organization mode requires the platform repository and generated repositories to have the same configured owner.'
  }
  try {
    $permission = Invoke-RestMethod -Method Get -Uri "https://api.github.com/repos/$($platformParts[0])/$($platformParts[1])/collaborators/$Requester/permission" -Headers $headers
    if ($permission.permission -notin @('admin', 'maintain', 'write')) {
      throw "Requester $Requester does not have write-equivalent access to the platform request workflow."
    }
  }
  catch { throw "Could not prove requester authorization on the platform repository; failing closed. $($_.Exception.Message)" }
}

$requestStarted = [DateTimeOffset]::UtcNow
$description = "Disposable golden-path environment $EnvironmentId generated by azure-platform-engineering-lab"
$body = @{
  owner = $owner
  name = $RepositoryName
  description = $description
  include_all_branches = $false
  private = $false
} | ConvertTo-Json

function Get-ExactGeneratedRepository {
  try {
    $candidateResponse = Invoke-WebRequest -Method Get -Uri "https://api.github.com/repos/$owner/$RepositoryName" -Headers $headers -SkipHttpErrorCheck -StatusCodeVariable candidateStatus
  }
  catch { throw "REPOSITORY_READBACK_TRANSIENT: $($_.Exception.Message)" }
  if ($candidateStatus -eq 404) { return $null }
  if ($candidateStatus -in @(408, 429, 500, 502, 503, 504)) { throw "REPOSITORY_READBACK_TRANSIENT: HTTP $candidateStatus" }
  if ($candidateStatus -ne 200) { throw "Generated-repository readback failed with non-retryable HTTP $candidateStatus." }
  $candidate = $candidateResponse.Content | ConvertFrom-Json
  $templateFullName = "$templateOwner/$templateName"
  if ($candidate.owner.login.ToLowerInvariant() -ne $owner.ToLowerInvariant() -or
      $candidate.name -ne $RepositoryName -or
      $candidate.description -ne $description -or
      $candidate.private -ne $false -or
      [string]$candidate.default_branch -ne 'main') {
    throw "Repository $owner/$RepositoryName appeared after an ambiguous request but lacks this environment's idempotency evidence."
  }
  $createdAt = [DateTimeOffset]::Parse([string]$candidate.created_at)
  if ($createdAt -lt $requestStarted.AddSeconds(-5)) {
    throw "Repository $owner/$RepositoryName predates this request and cannot be adopted."
  }
  Assert-AmbiguousRepositoryProvenance `
    -Repository $candidate `
    -ExpectedTemplate $templateFullName `
    -Headers $headers `
    -ExpectedTree $canonicalTree
  return $candidate
}

$absenceProbe = Invoke-WebRequest -Method Get -Uri "https://api.github.com/repos/$owner/$RepositoryName" -Headers $headers -SkipHttpErrorCheck -StatusCodeVariable absenceStatus
if ($absenceStatus -eq 200) { throw "Repository $owner/$RepositoryName already exists; refusing name-only adoption." }
if ($absenceStatus -ne 404) { throw "Could not prove repository-name absence before generation (HTTP $absenceStatus)." }

$repository = $null
$lastStatus = $null
foreach ($delay in @(0, 2, 4, 8, 16)) {
  if ($delay -gt 0) { Start-Sleep -Seconds $delay }
  & (Join-Path $PSScriptRoot 'Assert-ActiveLease.ps1') -Before 'calling the GitHub template-generation API'
  $env:REPOSITORY_GENERATION_POST_ATTEMPTED = 'true'
  try {
    $generateResponse = Invoke-WebRequest -Method Post -Uri "https://api.github.com/repos/$templateOwner/$templateName/generate" -Headers $headers -ContentType 'application/json' -Body $body -SkipHttpErrorCheck -StatusCodeVariable generateStatus
    $lastStatus = $generateStatus
    if ($generateStatus -eq 201) {
      $repository = $generateResponse.Content | ConvertFrom-Json
      break
    }
  }
  catch {
    $lastStatus = 'transport-error'
  }

  if ($lastStatus -eq 422) {
    try { $repository = Get-ExactGeneratedRepository }
    catch {
      if ($_.Exception.Message -match '^REPOSITORY_READBACK_TRANSIENT:') { $lastStatus = 'readback-transient'; continue }
      throw
    }
    if ($repository) { break }
    throw "Repository $owner/$RepositoryName collided without matching environment idempotency evidence."
  }
  if ($lastStatus -notin @(408, 429, 500, 502, 503, 504, 'transport-error')) {
    throw "GitHub template generation failed with non-retryable result $lastStatus."
  }
  try { $repository = Get-ExactGeneratedRepository }
  catch {
    if ($_.Exception.Message -match '^REPOSITORY_READBACK_TRANSIENT:') { $lastStatus = 'readback-transient'; continue }
    throw
  }
  if ($repository) { break }
}

if (-not $repository) {
  try { $repository = Get-ExactGeneratedRepository }
  catch {
    if ($_.Exception.Message -notmatch '^REPOSITORY_READBACK_TRANSIENT:') { throw }
    $lastStatus = 'readback-transient'
  }
}
if (-not $repository) { throw "AMBIGUOUS_REPOSITORY_CREATION: GitHub template generation or readback remained ambiguous after bounded retries (last result: $lastStatus)." }

if (-not $repository.id -or -not $repository.node_id -or $repository.owner.login -ne $owner -or [string]$repository.default_branch -ne 'main') {
  throw 'GitHub template response did not contain the expected immutable repository identity.'
}

$treeVerified = $false
$treeError = $null
foreach ($delay in @(0, 2, 4, 8, 16)) {
  if ($delay -gt 0) { Start-Sleep -Seconds $delay }
  try {
    Assert-ExactCanonicalTree -Headers $headers -RepositoryOwner ([string]$repository.owner.login) -RepositoryName ([string]$repository.name) -Expected $canonicalTree
    $treeVerified = $true
    break
  }
  catch { $treeError = $_.Exception.Message }
}
if (-not $treeVerified) {
  throw "GENERATED_CANONICAL_TREE_UNPROVEN: exact reviewed content could not be proven after bounded retries; attachment and deletion are forbidden. $treeError"
}

[ordered]@{
  owner = $repository.owner.login
  name = $repository.name
  numericId = [int64]$repository.id
  nodeId = $repository.node_id
  htmlUrl = $repository.html_url
  provenanceVerified = $true
} | ConvertTo-Json -Compress
