[CmdletBinding()]
param(
  [Parameter(Mandatory)] [string] $RecordJson
)

$ErrorActionPreference = 'Stop'
$record = $RecordJson | ConvertFrom-Json
if ($record.phase -ne 'REQUESTED' -or $record.repository) {
  throw 'Only a REQUESTED environment without an attached repository identity may resolve its UUID repository claim.'
}
foreach ($name in @('GITHUB_TOKEN', 'GENERATED_REPOSITORY_OWNER', 'TEMPLATE_REPOSITORY_OWNER', 'TEMPLATE_REPOSITORY_NAME')) {
  if (-not [Environment]::GetEnvironmentVariable($name)) { throw "$name is required for pending-repository resolution." }
}
& (Join-Path $PSScriptRoot 'Assert-ActiveLease.ps1') -Before 'resolving an ambiguous generated-repository claim'

$headers = @{
  Authorization = "Bearer $($env:GITHUB_TOKEN)"
  Accept = 'application/vnd.github+json'
  'X-GitHub-Api-Version' = '2026-03-10'
}
$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$canonicalRoot = Join-Path $root 'scaffolds/application/base'
. (Join-Path $PSScriptRoot 'GitHubRepositoryProvenance.ps1')
$canonicalTree = Get-CanonicalTree -CanonicalRoot $canonicalRoot
$owner = $env:GENERATED_REPOSITORY_OWNER
$name = $record.requestedRepositoryName
try {
  $response = Invoke-WebRequest -Method Get -Uri "https://api.github.com/repos/$owner/$name" -Headers $headers -SkipHttpErrorCheck -StatusCodeVariable status
}
catch { throw "AMBIGUOUS_REPOSITORY_CREATION: pending repository readback transport failure. $($_.Exception.Message)" }
if ($status -eq 404) {
  $age = [DateTimeOffset]::UtcNow - [DateTimeOffset]::Parse($record.createdAt)
  $result = if ($age.TotalMinutes -ge 15) { 'absent-safe' } else { 'pending' }
  [ordered]@{ status = $result; repository = $null } | ConvertTo-Json -Depth 5 -Compress
  return
}
if ($status -in @(408, 429, 500, 502, 503, 504)) { throw "AMBIGUOUS_REPOSITORY_CREATION: pending repository readback is transiently unavailable (HTTP $status)." }
if ($status -ne 200) { throw "AMBIGUOUS_REPOSITORY_CREATION: pending repository readback failed with non-retryable HTTP $status." }

$repository = $response.Content | ConvertFrom-Json
$expectedDescription = "Disposable golden-path environment $($record.environmentId) generated by azure-platform-engineering-lab"
$expectedTemplate = "$($env:TEMPLATE_REPOSITORY_OWNER)/$($env:TEMPLATE_REPOSITORY_NAME)"
if ($repository.owner.login.ToLowerInvariant() -ne $owner.ToLowerInvariant() -or
    $repository.name -ne $name -or
    $repository.description -ne $expectedDescription -or
    $repository.private -ne $false) {
  throw 'AMBIGUOUS_REPOSITORY_CREATION: the repository name resolves without this environment claim; immutable adoption is forbidden.'
}
if ([DateTimeOffset]::Parse([string]$repository.created_at) -lt [DateTimeOffset]::Parse($record.createdAt).AddSeconds(-5)) {
  throw 'AMBIGUOUS_REPOSITORY_CREATION: the pending repository predates the environment claim; adoption is forbidden.'
}
try {
  Assert-AmbiguousRepositoryProvenance `
    -Repository $repository `
    -ExpectedTemplate $expectedTemplate `
    -Headers $headers `
    -ExpectedTree $canonicalTree
}
catch {
  throw "AMBIGUOUS_REPOSITORY_CREATION: exact reviewed template provenance and canonical content could not be proven; immutable attachment and deletion are forbidden. $($_.Exception.Message)"
}

[ordered]@{
  status = 'resolved'
  repository = [ordered]@{
    owner = $repository.owner.login
    name = $repository.name
    numericId = [int64]$repository.id
    nodeId = $repository.node_id
    htmlUrl = $repository.html_url
    provenanceVerified = $true
  }
} | ConvertTo-Json -Depth 8 -Compress
